//
//  Configuration.h
//  RewardSciencesAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
//
#ifndef RewardSciencesAPI_Configuration_h
#define RewardSciencesAPI_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

/** extern reference to the config variable Accept */
extern NSString* Configuration_Accept;

/** extern reference to the config variable ContentType */
extern NSString* Configuration_ContentType;

/** The OAuth 2.0 access token to be set before API calls */
/** extern reference to the config variable OAuthAccessToken */
extern NSString* Configuration_OAuthAccessToken;

#endif
