//
//  Configuration.m
//  RewardSciencesAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
//
#import "Configuration.h"

/** The base Uri for API calls */
NSString* Configuration_BaseUri = @"https://api.rewardsciences.com";

/** Replace the value of Accept with an appropriate value */
NSString* Configuration_Accept = @"application/vnd.rewardsciences.v1+json";

/** Replace the value of ContentType with an appropriate value */
NSString* Configuration_ContentType = @"application/json";

/** The OAuth 2.0 access token to be set before API calls */
/** Replace the value of OAuthAccessToken with an appropriate value */
NSString* Configuration_OAuthAccessToken = @"TODO: Replace";

