//
//  Activities.h
//  RewardSciencesAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface Activities : BaseController

/**
* Completion block definition for asynchronous call to Track */
typedef void (^CompletedPostTrack)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* This endpoint lets you track the activities your users perform.
* @param    userId    Required parameter: The ID of the user who is performing the activity.
* @param    activityType    Required parameter: The type of activity the user is performing. Example: 'purchased-a-product'
* @param    price    Optional parameter: The price related to the activity, if any. Expressed in USD
* @param    recordId    Optional parameter: The ID for the record associated with the activity in your database.
*/
- (void) trackAsyncWithUserId:(int) userId
                activityType:(NSString*) activityType
                price:(NSNumber*) price
                recordId:(NSString*) recordId
                completionBlock:(CompletedPostTrack) onCompleted;

@end