//
//  RewardCategories.h
//  RewardSciencesAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface RewardCategories : BaseController

/**
* Completion block definition for asynchronous call to List */
typedef void (^CompletedGetList)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* List all the available reward categories.
* @param    limit    Optional parameter: The number of reward categories you want to be retrieved.
* @param    offset    Optional parameter: The number of reward categories you want to skip before starting the retrieval.
*/
- (void) listAsyncWithLimit:(NSNumber*) limit
                offset:(NSNumber*) offset
                completionBlock:(CompletedGetList) onCompleted;

@end