//
//  Users.h
//  RewardSciencesAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface Users : BaseController

/**
* Completion block definition for asynchronous call to Show */
typedef void (^CompletedGetShow)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* This endpoint lets retrieve a user's details.
* @param    userId    Required parameter: The ID of the user to be retrieved.
*/
- (void) showAsyncWithUserId:(int) userId
                completionBlock:(CompletedGetShow) onCompleted;

/**
* Completion block definition for asynchronous call to Identify */
typedef void (^CompletedPostIdentify)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* This endpoint lets you tie a user with his/her activities. You’ll want to identify a user with any relevant information as soon as they log-in or sign-up.
* @param    email    Required parameter: The user's email address
* @param    firstName    Optional parameter: The user's first name
* @param    lastName    Optional parameter: The user's last name
*/
- (void) identifyAsyncWithEmail:(NSString*) email
                firstName:(NSString*) firstName
                lastName:(NSString*) lastName
                completionBlock:(CompletedPostIdentify) onCompleted;

@end